Repository zurvan-lab/timetrace, pull requests merged in 2023-10, with the labels that each got.

#45 fix: removed StringToBytes and BytesToString functions
  utils/random.go
Labels: enhancement, good first issue

#43 refactor: databse functions and data structure
  TODO.md
  cmd/main.go
  core/database/database.go
  core/database/element.go
  core/database/set.go
  core/database/subSets.go
  core/database/types.go
Labels: enhancement

#46 feat: add code owners for default review
  .github/CODEOWNERS
Labels: enhancement, CI/CD

#51 feat: document and logo
  .img/logo.svg
  README.md
Labels: documentation

#53 fix: Migrate go mod name to TimeTrace
  cmd/main.go
  config/config.go
  core/database/database.go
  go.mod
  go.sum
Labels: bug, enhancement, good first issue

#57 chore(CI): update pipeline
  .github/workflows/linting.yml
Labels: CI/CD, linting

#54 feat: config main functions and test
  .golangci.yml
  config/config.go
  config/config.yaml
  config/config_test.go
  log/logger_test.go
Labels: linting, test, config

#59 feat(docs): data structure and example
  .img/logo.svg
  README.md
  doc/TQL/.keep
  doc/config/.keep
  doc/main.md
  doc/model/model.md
  doc/usage/.keep
Labels: documentation

#60 chore: config structure updated
  config/config.go
  config/config.yaml
Labels: enhancement

#63 feat: config documents
  config/config.go
  config/config.yaml
  config/config_test.go
  doc/config/.keep
  doc/config/config.md
Labels: documentation, config
