Repository zurvan-lab/timetrace, pull requests merged in 2023-09, with the labels that each got.

#28 feat: golangci-linter config file
  .github/workflows/linting.yml
  .golangci.yml
  Makefile
  config/config.go
  core/database/subSets.go
Labels: CI/CD, linting

#35 feat: version.go file
  version.go
Labels: enhancement, good first issue

#37 fix: broken test
  version.go
Labels: bug
